name: Helm Package and Publish

on:
  push:
    branches:
      - feature/ghcr

jobs:
  package-helm-chart:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      

      - name: Login to GitHub Container Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Package and push helm chart
        run: |
          mkdir -p packaged
          helm package chart -d packaged
          chart_name=$(find -name  '*.tgz' -print)
          helm push $chart_name oci://ghcr.io/${{ github.repository }}         
  