name: Helm Package and Publish

on:
  push:
    branches:
      - main

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    permissions:
          contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Package Helm Chart
        run: |
          mkdir -p packaged
          helm package chart -d packaged

      - name: Move package to root
        run: |
          mv packaged/*.tgz .

      - name: Commit and Push
        run: |
          git config user.name "Domingos Neto"
          git config user.email "dofevine@hotmail.com"
          git add .
          git commit -m "Update and Push helm package"
          git push